# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-19 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DBfirst_name', models.CharField(max_length=255)),
                ('DBlast_name', models.CharField(max_length=255)),
                ('DBemail', models.CharField(max_length=255)),
                ('DBpassword', models.CharField(max_length=255)),
            ],
        ),
    ]
